/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.zipek.minicloud.forms;

import cz.zipek.minicloud.Forms;
import cz.zipek.minicloud.api.File;
import cz.zipek.minicloud.api.FileVersion;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.DefaultListModel;

/**
 *
 * @author Kamen
 */
public class FileVersionsFrame extends javax.swing.JFrame {

	private File file;
	
	/**
	 * Creates new form FileVersionsFrame
	 */
	public FileVersionsFrame() {
		initComponents();
	}
	
	public void setFile(File file) {
		this.file = file;
		
		DefaultListModel model = new DefaultListModel();

		for(FileVersion ver : file.getVersions()) {
			model.addElement(new SimpleDateFormat("dd.MM.YYYY HH:mm").format(ver.getCreated()));
		}
		
		listVersions.setModel(model);
		
		labelPath.setText(file.getPath());
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        listVersions = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        buttonDownload = new javax.swing.JButton();
        buttonClose = new javax.swing.JButton();
        labelPath = new javax.swing.JLabel();

        listVersions.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { "12.8.2015 10:12", "13.8.2015 12:30" };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        listVersions.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        listVersions.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listVersionsMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(listVersions);

        jLabel1.setText("File:");
        jLabel1.setToolTipText("");

        buttonDownload.setText("Download");
        buttonDownload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonDownloadActionPerformed(evt);
            }
        });

        buttonClose.setText("Close");
        buttonClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonCloseActionPerformed(evt);
            }
        });

        labelPath.setText("/folder/name.ext");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(labelPath))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonDownload)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 242, Short.MAX_VALUE)
                        .addComponent(buttonClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonDownload)
                    .addComponent(buttonClose))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void buttonCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonCloseActionPerformed
		setVisible(false);
    }//GEN-LAST:event_buttonCloseActionPerformed

    private void buttonDownloadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonDownloadActionPerformed
        int index = listVersions.getSelectedIndex();
		if (index >= 0) {
			List<FileVersion> versions = new ArrayList<>();
			versions.add(file.getVersions()[index]);
			
			Forms.showDownload(versions);
			
			setVisible(false);
		}
    }//GEN-LAST:event_buttonDownloadActionPerformed

    private void listVersionsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listVersionsMouseClicked
        if (evt.getClickCount() == 2) {
			buttonDownloadActionPerformed(null);
		}
    }//GEN-LAST:event_listVersionsMouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonClose;
    private javax.swing.JButton buttonDownload;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel labelPath;
    private javax.swing.JList listVersions;
    // End of variables declaration//GEN-END:variables
}
