/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.zipek.minicloud.forms;

import cz.zipek.minicloud.Manager;
import cz.zipek.minicloud.Session;
import cz.zipek.minicloud.Settings;
import cz.zipek.minicloud.api.Event;
import cz.zipek.minicloud.api.File;
import cz.zipek.minicloud.api.Listener;
import cz.zipek.minicloud.api.download.DownloadEvent;
import cz.zipek.minicloud.api.download.Downloader;
import cz.zipek.minicloud.api.events.ErrorEvent;
import cz.zipek.minicloud.api.events.SuccessEvent;
import cz.zipek.minicloud.api.upload.UploadEvent;
import cz.zipek.minicloud.api.upload.Uploader;
import cz.zipek.minicloud.api.upload.events.UploadFileDoneEvent;
import cz.zipek.minicloud.api.upload.events.UploadProgressEvent;
import java.io.IOException;
import java.io.PipedInputStream;
import java.io.PipedOutputStream;
import java.security.NoSuchAlgorithmException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.crypto.NoSuchPaddingException;
import javax.swing.JOptionPane;

/**
 *
 * @author Kamen
 */
public class FileAvaibilityFrame extends javax.swing.JFrame implements Listener {

	private final File file;
	private final boolean setPublic;

	private Uploader uploader;
	private Downloader downloader;
	
	private String actionId;
	
	/**
	 * Creates new form FileAvaibility
	 * @param listener frame that receives success state
	 * @param file file to be updated
	 * @param publ result publicity state state
	 */
	public FileAvaibilityFrame(FileFrame listener, File file, boolean publ) {
		initComponents();
		
		this.file = file;
		this.setPublic = publ;
		
		labelPath.setText(file.getPath());
		
		// Determine correct action
		if (setPublic) {
			file.setPublic(setPublic);
			
			if (file.isEncrypted()) {
				prepareReupload(false);
			} else {
				file.save();
			}
		} else {
			prepareReupload(true);
		}
	}
	
	private void prepareReupload(boolean encrypt) {
		
		try {
			uploader = new Uploader(Manager.external, encrypt ? Session.getUser().getEncryptor(Settings.getEncryption()) : null);
			downloader = new Downloader(Manager.external, Session.getUser());
			
			PipedInputStream input = new PipedInputStream();
			PipedOutputStream output = new PipedOutputStream(input);
			
			downloader.add(file, output);
			uploader.add(input, file);
			
			downloader.start(null);
			uploader.start(null);
		} catch (NoSuchAlgorithmException | NoSuchPaddingException | IOException ex) {
			Logger.getLogger(FileAvaibilityFrame.class.getName()).log(Level.SEVERE, null, ex);
		}
		
	}
	
	@Override
	public void handleEvent(Object event, Object sender) {
		
		if (event instanceof DownloadEvent)
			handleDownload((DownloadEvent)event);
		else if (event instanceof UploadEvent)
			handleUpload((UploadEvent)event);
		else
			handleExternal((Event)event);
		
	}
	
	private void handleDownload(DownloadEvent event) {
		
	}
	
	private void handleUpload(UploadEvent event) {
		
		if (event instanceof UploadProgressEvent) {
			UploadProgressEvent e = (UploadProgressEvent) event;
			int done = (int)((e.getSent()* 100.0) / e.getTotal());
			
			progressState.setValue(done);
			labelState.setText("Reuploading ... " + done + "%");
		}
		
		if (event instanceof UploadFileDoneEvent) {
			labelState.setText("Reupload done. Saving result ...");
			progressState.setValue(100);
			
			actionId = file.save();
		}
		
	}
	
	private void handleExternal(Event event) {
		
		if (event.getActionId().equals(actionId)) {
			if (event instanceof SuccessEvent) {
				
				JOptionPane.showMessageDialog(
						this,
						"File was successfuly reuploaded.",
						"Done",
						JOptionPane.INFORMATION_MESSAGE
				);
			
				setVisible(false);
				
			} else {
				
				JOptionPane.showMessageDialog(
						this,
						"Error occured when saving result. File is now corrupted. Error: " + ((ErrorEvent)event).getMessage(),
						"Done",
						JOptionPane.ERROR_MESSAGE
				);
				
				setVisible(false);
				
			}
			
			actionId = null;
			
			Manager.external.removeListener(this);
		}
		
	}

	/**
	 * This method is called from within the constructor to initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is always
	 * regenerated by the Form Editor.
	 */
	@SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        labelPath = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        progressState = new javax.swing.JProgressBar();
        labelState = new javax.swing.JLabel();
        buttonStart = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Update file publicity");
        setMinimumSize(getPreferredSize());

        jLabel1.setText("Converted file:");

        labelPath.setText("/storage/path/file.ext");

        jLabel3.setText("Required action:");

        jLabel4.setText("Reupload");

        jLabel5.setText("<html>\nFile is stored on server in encrypted format. You'll need to reupload it to make it public.<br>\nPublic files are stored unencrypted.\n</html>");
        jLabel5.setVerticalAlignment(javax.swing.SwingConstants.TOP);

        labelState.setText("Ready");

        buttonStart.setText("Start");
        buttonStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonStartActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel3))
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelPath, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(progressState, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addComponent(labelState)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(buttonStart))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelPath))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(progressState, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelState)
                    .addComponent(buttonStart))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonStartActionPerformed

		labelState.setText("Reuploading...");
		Manager.external.addListener(this);
		
    }//GEN-LAST:event_buttonStartActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonStart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel labelPath;
    private javax.swing.JLabel labelState;
    private javax.swing.JProgressBar progressState;
    // End of variables declaration//GEN-END:variables

}
